version: 1.11.0.{build}

clone_folder: C:\gopath\src\github.com\zchee\go-xdgbasedir
shallow_clone: true

environment:
  GOPATH: C:\gopath
  GO_VERSION: 1.11.0
  PATH: C:\go\bin;C:\gopath\bin;%PATH%;%PYTHON%;%PYTHON%\Scripts

stack: go 1.11.0

build: off

before_test:
  - go get -u github.com/golang/lint/golint

test_script:
  - gofmt -s -l -w .
  - go vet -v -all .
  - golint -min_confidence=0.3 -set_exit_status ./...

after_test:
  - go test -v -race -covermode=atomic -coverpkg=./... -coverprofile=coverage.out ./...

on_success:
  - pip install -U codecov
  - codecov -f coverage.out -F windows
